using System.Text;
using System.Text.RegularExpressions;
using Tomlyn;
using Tomlyn.Model;

namespace AiResume.Wrapper;

/// <summary>
/// S6-A cc-connect 配置契约模型(与 S4-A 试点实证形状一致):
/// 1 个 feishu 平台 + N 个 agent 项目;凭据只经参数注入并写入仓库外路径,
/// 模型本身不提供任何默认凭据。
/// </summary>
/// <summary>
/// 飞书平台选项。<paramref name="AllowFrom"/> 是**逗号分隔的 open_id 字符串**
/// (不是数组),<c>"*"</c> 表示放行所有人。
///
/// **不允许为空**:cc-connect 在未设置时会打印
/// 「allow_from is not set — all users are permitted」并放行所有人,
/// 而现役系统是靠 feishuAuthOpenIds 锁死的。空值等于把 12 个项目目录的
/// 读写权限开放给任何能给机器人发消息的人(2026-08-06 切换时实测到,暴露约 90 秒)。
/// </summary>
public sealed record CcConnectPlatformOptions(string AppId, string AppSecret, string AllowFrom);

/// <summary>
/// cc-connect 项目定义([[projects]]);agent 取值如 claudecode/codex。
///
/// <paramref name="AdminFrom"/> 控制 /shell、/dir 等特权命令,同样是逗号分隔字符串。
/// **必须写在 [[projects]] 这一层**——上游文档明确警告:放进
/// [projects.platforms.options] 会被静默忽略。
/// </summary>
public sealed record CcConnectProject(
    string Name, string Agent, string WorkDir, string Mode = "default", string AdminFrom = "",
    IReadOnlyList<string>? ProviderRefs = null, string SelectedProvider = "", string SelectedModel = "");

/// <summary>cc-connect 整体配置输入;Render 输出确定性 TOML(相同输入 → 相同字节)。</summary>
public sealed record CcConnectConfig(IReadOnlyList<CcConnectProject> Projects, CcConnectPlatformOptions Feishu)
{
    public static void Validate(CcConnectConfig config)
    {
        ArgumentNullException.ThrowIfNull(config);
        ArgumentNullException.ThrowIfNull(config.Feishu);
        if (string.IsNullOrWhiteSpace(config.Feishu.AppId))
        {
            throw new ArgumentException("飞书 app_id 不得为空。", nameof(config));
        }

        if (string.IsNullOrWhiteSpace(config.Feishu.AppSecret))
        {
            throw new ArgumentException("飞书 app_secret 不得为空。", nameof(config));
        }

        // fail-closed:空 allow_from 会让 cc-connect 放行所有人。宁可拒绝生成配置,
        // 也不产出一份"任何人都能驱动 Claude Code 改你项目"的配置。
        if (string.IsNullOrWhiteSpace(config.Feishu.AllowFrom))
        {
            throw new ArgumentException(
                "allow_from 不得为空:cc-connect 未设置该项时会放行所有飞书用户。", nameof(config));
        }

        if (config.Projects.Count == 0)
        {
            throw new ArgumentException("至少需要 1 个项目。", nameof(config));
        }

        foreach (CcConnectProject project in config.Projects)
        {
            if (string.IsNullOrWhiteSpace(project.Name) || string.IsNullOrWhiteSpace(project.WorkDir))
            {
                throw new ArgumentException("项目 name/work_dir 不得为空。", nameof(config));
            }
        }
    }
}

/// <summary>
/// S6-A cc-connect config.toml 确定性生成器:
/// - Render 只依赖输入(无时间戳/随机量),相同输入产出相同字节(便于对账与测试);
/// - Write 落仓库外路径:临时文件 + 原子替换(File.Move overwrite),
///   任何时刻磁盘上要么旧完整内容要么新完整内容(对齐现役 config.json 写纪律);
/// - RenderSanitized 供日志/测试展示,凭据一律 [REDACTED],实值零出现。
/// </summary>
public static class CcConnectConfigGenerator
{
    private sealed record ProjectPreservation(
        IReadOnlyList<string> ProjectLines,
        IReadOnlyList<string> AgentLines,
        IReadOnlyList<string> AgentOptionLines,
        IReadOnlyList<KeyValuePair<string, string>> AgentEnvironment,
        IReadOnlyList<string> AdditionalBlocks,
        IReadOnlyList<string> ForeignPlatforms)
    {
        public static readonly ProjectPreservation Empty = new(
            Array.Empty<string>(), Array.Empty<string>(), Array.Empty<string>(),
            Array.Empty<KeyValuePair<string, string>>(), Array.Empty<string>(), Array.Empty<string>());
    }

    /// <summary>
    /// 生成标记行。保留既有内容时要按它剔除上一轮写入的那行,否则每次生成都会多一行,
    /// 逐轮累积成一叠重复注释。
    /// </summary>
    private const string GeneratedMarker = "# Generated by AiResume.Wrapper";

    /// <summary>生成确定性 TOML 文本(含真实凭据;只允许写仓库外路径,不得进日志)。</summary>
    public static string Render(CcConnectConfig config) => RenderCore(config, redact: false);

    /// <summary>生成脱敏 TOML 文本(app_secret/敏感值置换 [REDACTED]),供日志与断言展示。</summary>
    public static string RenderSanitized(CcConnectConfig config) => RenderCore(config, redact: true);

    /// <summary>
    /// 带「保留了几个非飞书平台」计数的脱敏渲染。
    ///
    /// 计数必须露出来:用户点「生成 cc-connect 配置」后只看得到这份回显,
    /// 如果扫码绑好的微信平台被保留了却只字不提,沉默会被读成"它没了"——
    /// 于是又去扫一次码。**保留块本身绝不回显**:它的 options 里有 bearer token。
    /// </summary>
    public static string RenderSanitized(CcConnectConfig config, int foreignPlatformCount)
        => RenderCore(config, redact: true,
            ProjectPreservation.Empty with
            {
                ForeignPlatforms = foreignPlatformCount > 0
                    ? new string[foreignPlatformCount]
                    : Array.Empty<string>(),
            });

    /// <summary>
    /// 原子写入仓库外路径(临时文件 + 原子替换);路径与内容均不入仓库。
    ///
    /// **保留我们不管的段落**:目标文件已存在时,原样保留除 <c>[[projects]]</c> 之外的
    /// 全部内容——`[management]`(9820 端口的 Web 管理台)、`[log]`、`[speech]`、`[tts]`、
    /// webhook、hooks、顶层的 data_dir/language 等等。
    ///
    /// 2026-08-06 切换时踩到:本方法原本整份覆盖,只写 [[projects]],
    /// 把用户已启用的 `[management]` 一并抹掉,admin 页 http://localhost:9820 直接打不开。
    /// **这份配置不归我们独占**——我们只拥有项目清单这一部分,其余是 cc-connect 与用户的。
    ///
    /// 同理,`cc-connect weixin setup` 扫码绑定的微信平台也属于用户资产:
    /// 整块重写 [[projects]] 时若把它丢掉,用户下次扫码绑定就白做了。
    /// 所以这里把非飞书平台块原样抽出来,追加到生成的飞书块之后。
    /// </summary>
    public static void Write(
        string path,
        CcConnectConfig config,
        bool preserveAgentSelection = true,
        Func<string, string?>? validateCandidate = null,
        bool preserveInlineAgentProviders = true)
    {
        ArgumentException.ThrowIfNullOrEmpty(path);
        CcConnectConfig.Validate(config);
        string? directory = Path.GetDirectoryName(path);
        if (!string.IsNullOrEmpty(directory))
        {
            Directory.CreateDirectory(directory);
        }

        string preserved = string.Empty;
        ProjectPreservation projectPreservation = ProjectPreservation.Empty;
        if (File.Exists(path))
        {
            try
            {
                string existing = File.ReadAllText(path);
                if (!preserveInlineAgentProviders &&
                    HasInlineAgentProviders(existing, config.Projects.FirstOrDefault()?.Name ?? string.Empty))
                {
                    throw new InvalidDataException(
                        "切换 agent 时发现项目内联 provider;它不受全局 agent_types 过滤。请先将该 provider 迁移为带 agent_types/endpoints 的全局 [[providers]],或手动移除后重试。");
                }
                preserved = ExtractNonProjectSections(existing);
                projectPreservation = ExtractProjectPreservation(
                    existing,
                    preserveAgentSelection,
                    preserveInlineAgentProviders,
                    config.Projects.FirstOrDefault()?.Name ?? string.Empty);
                preserved = EnsureSelectableProviderModels(preserved, config);
            }
            catch (IOException)
            {
                // 读不到旧文件:退化成只写项目段。宁可少保留,也不要因此写不出配置。
                preserved = string.Empty;
                projectPreservation = ProjectPreservation.Empty;
            }
        }

        string content = RenderCore(config, redact: false, projectPreservation);
        if (!string.IsNullOrWhiteSpace(preserved))
        {
            content = preserved.TrimEnd() + Environment.NewLine + Environment.NewLine + content;
        }

        string tmp = path + ".tmp-" + Guid.NewGuid().ToString("N");
        try
        {
            using (var stream = new FileStream(tmp, FileMode.CreateNew, FileAccess.Write, FileShare.None))
            using (var writer = new StreamWriter(
                stream,
                new UTF8Encoding(encoderShouldEmitUTF8Identifier: false),
                bufferSize: 4096,
                leaveOpen: true))
            {
                writer.Write(content);
                writer.Flush();
                stream.Flush(flushToDisk: true);
            }
            string? validationError = validateCandidate?.Invoke(tmp);
            if (!string.IsNullOrWhiteSpace(validationError))
            {
                throw new InvalidDataException(validationError);
            }

            File.Move(tmp, path, overwrite: true);
        }
        finally
        {
            if (File.Exists(tmp))
            {
                try
                {
                    File.Delete(tmp);
                }
                catch
                {
                    // 替换已完成;残留 tmp 清理失败不抛出。
                }
            }
        }
    }

    /// <summary>
    /// 从既有 TOML 中剔除全部 <c>[[projects]]</c> 及其子表(<c>[projects.*]</c>),
    /// 其余内容原样返回。
    ///
    /// 只做行级切分而不做完整 TOML 解析:我们要的是"原样保留",一旦解析再序列化,
    /// 用户的注释、段落顺序和格式就全没了——而这份文件里的注释正是 cc-connect
    /// 自带的使用说明。同理也剔除我们自己上一轮写入的生成标记行,避免逐轮累积。
    /// </summary>
    private static readonly HashSet<string> OwnedProjectKeys = new(StringComparer.Ordinal)
    {
        "name", "admin_from",
    };

    private static readonly HashSet<string> OwnedAgentKeys = new(StringComparer.Ordinal)
    {
        "type", "provider_refs",
    };

    private static readonly HashSet<string> OwnedAgentOptionKeys = new(StringComparer.Ordinal)
    {
        "mode", "work_dir", "env",
    };

    /// <summary>
    /// 按上游的精确、first-match 项目语义保留 AI Resume 不拥有的项目配置。
    /// 项目顶层、agent、agent options 和自定义子表分别保存并写回原层级，禁止扁平化搬家。
    /// </summary>
    private static ProjectPreservation ExtractProjectPreservation(
        string existingToml,
        bool preserveAgentSelection,
        bool preserveInlineAgentProviders,
        string projectName)
    {
        if (!TryFindProjectBlock(existingToml, projectName, out string[] lines, out int start, out int end))
        {
            return ProjectPreservation.Empty;
        }

        var headers = new List<int> { start };
        for (int i = start + 1; i < end; i++)
        {
            if (lines[i].TrimStart().StartsWith('['))
            {
                headers.Add(i);
            }
        }
        headers.Add(end);

        var projectLines = new List<string>();
        var agentLines = new List<string>();
        var optionLines = new List<string>();
        var additional = new List<string>();
        var foreignPlatforms = new List<string>();
        IReadOnlyList<KeyValuePair<string, string>> agentEnvironment =
            ReadProjectAgentEnvironment(existingToml, projectName);

        for (int h = 0; h + 1 < headers.Count; h++)
        {
            int sectionStart = headers[h];
            int sectionEnd = headers[h + 1];
            string header = lines[sectionStart];

            if (HeaderEquals(header, array: true, "projects"))
            {
                projectLines.AddRange(FilterOwnedLines(lines, sectionStart + 1, sectionEnd, OwnedProjectKeys));
            }
            else if (HeaderEquals(header, array: false, "projects", "agent"))
            {
                agentLines.AddRange(FilterOwnedLines(lines, sectionStart + 1, sectionEnd, OwnedAgentKeys));
            }
            else if (HeaderEquals(header, array: false, "projects", "agent", "options"))
            {
                var owned = new HashSet<string>(OwnedAgentOptionKeys, StringComparer.Ordinal);
                if (!preserveAgentSelection)
                {
                    owned.Add("provider");
                    owned.Add("model");
                }
                optionLines.AddRange(FilterOwnedLines(lines, sectionStart + 1, sectionEnd, owned));
            }
            else if (HeaderEquals(header, array: false, "projects", "agent", "options", "env"))
            {
                // 结构化读取并在渲染时合并;不能把旧表原文再追加一次形成重复表。
            }
            else if (HeaderEquals(header, array: true, "projects", "platforms"))
            {
                int platformEnd = sectionEnd;
                while (h + 2 < headers.Count &&
                       HeaderStartsWithPath(lines[headers[h + 1]], "projects", "platforms") &&
                       !HeaderEquals(lines[headers[h + 1]], array: true, "projects", "platforms"))
                {
                    h++;
                    platformEnd = headers[h + 1];
                }

                string block = JoinTrimmedBlock(lines, sectionStart, platformEnd);
                string? platformType = ReadStringAssignment(block, "type");
                if (!string.Equals(platformType, "feishu", StringComparison.Ordinal))
                {
                    foreignPlatforms.Add(block);
                }
            }
            else if (HeaderStartsWithPath(header, "projects", "agent", "providers"))
            {
                if (!preserveInlineAgentProviders)
                {
                    throw new InvalidDataException(
                        "切换 agent 时发现项目内联 provider;它不受全局 agent_types 过滤。请先将该 provider 迁移为带 agent_types/endpoints 的全局 [[providers]],或手动移除后重试。");
                }
                additional.Add(JoinTrimmedBlock(lines, sectionStart, sectionEnd));
            }
            else if (!HeaderStartsWithPath(header, "projects", "platforms"))
            {
                additional.Add(JoinTrimmedBlock(lines, sectionStart, sectionEnd));
            }
        }

        return new ProjectPreservation(
            TrimBlankEdges(projectLines),
            TrimBlankEdges(agentLines),
            TrimBlankEdges(optionLines),
            agentEnvironment,
            additional.Where(block => block.Length > 0).ToArray(),
            foreignPlatforms.Where(block => block.Length > 0).ToArray());
    }

    private static IReadOnlyList<KeyValuePair<string, string>> ReadProjectAgentEnvironment(
        string existingToml,
        string projectName)
    {
        TomlTable root = TomlSerializer.Deserialize<TomlTable>(existingToml) ?? new TomlTable();
        if (!root.TryGetValue("projects", out object? rawProjects) || rawProjects is not TomlTableArray projects)
        {
            return Array.Empty<KeyValuePair<string, string>>();
        }

        TomlTable? project = projects.OfType<TomlTable>().FirstOrDefault(candidate =>
            projectName.Length == 0 ||
            (candidate.TryGetValue("name", out object? rawName) && rawName is string name &&
             name.Equals(projectName, StringComparison.Ordinal)));
        if (project is null || !project.TryGetValue("agent", out object? rawAgent) || rawAgent is not TomlTable agent ||
            !agent.TryGetValue("options", out object? rawOptions) || rawOptions is not TomlTable options ||
            !options.TryGetValue("env", out object? rawEnvironment))
        {
            return Array.Empty<KeyValuePair<string, string>>();
        }

        if (rawEnvironment is not TomlTable environment)
        {
            throw new InvalidDataException("projects.agent.options.env 必须是字符串键值表");
        }

        var result = new List<KeyValuePair<string, string>>();
        foreach ((string key, object? value) in environment)
        {
            if (key.Equals("AI_RESUME_INTERNAL_RUN", StringComparison.Ordinal))
            {
                continue;
            }
            if (value is not string text)
            {
                throw new InvalidDataException($"projects.agent.options.env.{key} 必须是字符串");
            }
            result.Add(new KeyValuePair<string, string>(key, text));
        }
        return result;
    }

    private static bool HasInlineAgentProviders(string existingToml, string projectName)
    {
        TomlTable root = TomlSerializer.Deserialize<TomlTable>(existingToml) ?? new TomlTable();
        if (!root.TryGetValue("projects", out object? rawProjects) ||
            rawProjects is not TomlTableArray projects)
        {
            return false;
        }

        TomlTable? project = projects.OfType<TomlTable>().FirstOrDefault(candidate =>
            candidate.TryGetValue("name", out object? rawName) && rawName is string name &&
            name.Equals(projectName, StringComparison.Ordinal));
        if (project is null || !project.TryGetValue("agent", out object? rawAgent) ||
            rawAgent is not TomlTable agent)
        {
            return false;
        }

        return agent.ContainsKey("providers");
    }

    /// <summary>兼容旧测试/调用方：仅返回仍保留的赋值行，不参与生产渲染。</summary>
    public static IReadOnlyList<string> ExtractProjectExtraKeys(
        string existingToml,
        bool preserveAgentSelection = true,
        string projectName = "")
    {
        ProjectPreservation p = ExtractProjectPreservation(
            existingToml, preserveAgentSelection, preserveInlineAgentProviders: true, projectName: projectName);
        return p.ProjectLines.Concat(p.AgentLines).Concat(p.AgentOptionLines)
            .Select(line => line.Trim())
            .Where(line => line.Contains('=') && !line.StartsWith('#'))
            .Distinct(StringComparer.Ordinal)
            .ToArray();
    }

    private static bool TryFindProjectBlock(
        string toml,
        string projectName,
        out string[] lines,
        out int start,
        out int end)
    {
        lines = (toml ?? string.Empty).Replace("\r\n", "\n").Split('\n');
        start = end = -1;
        try
        {
            TomlTable root = TomlSerializer.Deserialize<TomlTable>(toml ?? string.Empty) ?? new TomlTable();
            if (!root.TryGetValue("projects", out object? raw) || raw is not TomlTableArray projects)
            {
                return false;
            }

            int projectIndex = -1;
            for (int i = 0; i < projects.Count; i++)
            {
                if (projects[i] is TomlTable project &&
                    (projectName.Length == 0 ||
                     (project.TryGetValue("name", out object? rawName) && rawName is string name &&
                      name.Equals(projectName, StringComparison.Ordinal))))
                {
                    projectIndex = i;
                    break;
                }
            }

            if (projectIndex < 0)
            {
                return false;
            }

            int seen = -1;
            for (int i = 0; i < lines.Length; i++)
            {
                if (!HeaderEquals(lines[i], array: true, "projects"))
                {
                    continue;
                }

                seen++;
                if (seen == projectIndex)
                {
                    start = i;
                    break;
                }
            }

            if (start < 0)
            {
                return false;
            }

            end = lines.Length;
            for (int i = start + 1; i < lines.Length; i++)
            {
                string header = lines[i].TrimStart();
                if (!header.StartsWith('['))
                {
                    continue;
                }

                if (HeaderEquals(header, array: true, "projects") ||
                    !HeaderStartsWithPath(header, "projects"))
                {
                    end = i;
                    break;
                }
            }

            return true;
        }
        catch (Exception)
        {
            start = end = -1;
            return false;
        }
    }

    private static IReadOnlyList<string> FilterOwnedLines(
        string[] lines,
        int start,
        int end,
        IReadOnlySet<string> owned)
    {
        var result = new List<string>();
        for (int i = start; i < end; i++)
        {
            string trimmed = lines[i].Trim();
            if (!trimmed.StartsWith('#') && owned.Any(key => AssignmentKeyEquals(trimmed, key)))
            {
                continue;
            }
            result.Add(lines[i]);
        }
        return result;
    }

    private static IReadOnlyList<string> TrimBlankEdges(IReadOnlyList<string> lines)
    {
        int start = 0;
        int end = lines.Count;
        while (start < end && string.IsNullOrWhiteSpace(lines[start])) start++;
        while (end > start && string.IsNullOrWhiteSpace(lines[end - 1])) end--;
        return lines.Skip(start).Take(end - start).ToArray();
    }

    private static string JoinTrimmedBlock(string[] lines, int start, int end) =>
        string.Join(Environment.NewLine, TrimBlankEdges(lines[start..end])).Trim();

    private static bool HeaderEquals(string line, bool array, params string[] path)
    {
        string open = array ? @"\[\[" : @"\[";
        string close = array ? @"\]\]" : @"\]";
        return Regex.IsMatch(
            line,
            @"^\s*" + open + @"\s*" + HeaderPathPattern(path) + @"\s*" + close + @"\s*(?:#.*)?$",
            RegexOptions.CultureInvariant);
    }

    private static bool HeaderStartsWithPath(string line, params string[] path) => Regex.IsMatch(
        line,
        @"^\s*\[\[?\s*" + HeaderPathPattern(path) +
        @"(?:\s*\.\s*[^\]]+)?\s*\]\]?\s*(?:#.*)?$",
        RegexOptions.CultureInvariant);

    private static string HeaderPathPattern(IEnumerable<string> path) => string.Join(
        @"\s*\.\s*",
        path.Select(segment =>
            "(?:" + Regex.Escape(segment) + "|\"" + Regex.Escape(segment) + "\"|'" +
            Regex.Escape(segment) + "')"));

    private static bool AssignmentKeyEquals(string line, string key) => Regex.IsMatch(
        line,
        @"^\s*" + QuotedOrBareKeyPattern(key) + @"\s*=",
        RegexOptions.CultureInvariant);

    private static string QuotedOrBareKeyPattern(string key) =>
        "(?:" + Regex.Escape(key) + "|\"" + Regex.Escape(key) + "\"|'" + Regex.Escape(key) + "')";

    private static string? ReadStringAssignment(string text, string key)
    {
        var match = System.Text.RegularExpressions.Regex.Match(
            text,
            "^\\s*" + QuotedOrBareKeyPattern(key) +
            "\\s*=\\s*(?:\"(?<double>[^\"]*)\"|'(?<single>[^']*)')",
            System.Text.RegularExpressions.RegexOptions.Multiline);
        return !match.Success
            ? null
            : match.Groups["double"].Success ? match.Groups["double"].Value : match.Groups["single"].Value;
    }

    internal static string ExtractNonProjectSections(string existingToml)
    {
        var kept = new List<string>();
        bool inProjectBlock = false;

        foreach (string line in existingToml.Replace("\r\n", "\n").Split('\n'))
        {
            string trimmed = line.TrimStart();

            if (trimmed.StartsWith('['))
            {
                // 顶层表头出现:重新判定是否落在 projects 区域内。
                inProjectBlock = HeaderStartsWithPath(line, "projects");
            }

            if (inProjectBlock)
            {
                continue;
            }

            if (trimmed.StartsWith(GeneratedMarker, StringComparison.Ordinal))
            {
                continue;
            }

            kept.Add(line);
        }

        return string.Join(Environment.NewLine, kept).Trim();
    }

    /// <summary>
    /// 从既有 config.toml 里原样抽出**非 feishu** 的 [[projects.platforms]] 块。
    /// 逐块返回原始文本(含表头行),块之间不含额外空行。没有则返回空列表。
    ///
    /// 为什么必须逐行扫描而不是跨行正则:真实文件里 [[projects.platforms]] 与
    /// [projects.platforms.options] 等表头互相嵌套,跨行匹配会越过表边界,
    /// 把别的表的内容误并进来。逐行扫描天然尊重表边界。
    ///
    /// 为什么未知类型也保留:取不到 type 时宁可多留不可丢——丢了等于用户白扫一次码。
    /// </summary>
    public static IReadOnlyList<string> ExtractForeignPlatforms(string existingToml, string projectName = "")
    {
        return ExtractProjectPreservation(
            existingToml, preserveAgentSelection: true, preserveInlineAgentProviders: true, projectName: projectName)
            .ForeignPlatforms;
    }

    /// <summary>
    /// 从既有 config.toml 里读回 [projects.agent.options] 的 work_dir。
    /// 读不到返回 null。
    ///
    /// 只认 [projects.agent.options] 这张表下面的 work_dir;文件其它位置出现的
    /// work_dir 一律忽略。实现是逐行扫描:先定位到 [projects.agent.options] 行,
    /// 然后在遇到下一个表头行之前查找 work_dir 赋值行。
    ///
    /// **不可写成跨行正则**:真实文件里 [[projects.platforms]] 等表头夹在中间,
    /// 跨行匹配会越过表边界读到别的表的值。
    /// </summary>
    public static string? TryReadExistingWorkDir(string existingToml, string projectName = "")
    {
        if (string.IsNullOrEmpty(existingToml))
        {
            return null;
        }

        try
        {
            TomlTable root = TomlSerializer.Deserialize<TomlTable>(existingToml) ?? new TomlTable();
            TomlTable? project = null;
            if (root.TryGetValue("projects", out object? rawProjects))
            {
                if (rawProjects is TomlTableArray projects)
                {
                    project = projects.OfType<TomlTable>().FirstOrDefault(candidate =>
                        projectName.Length == 0 ||
                        (candidate.TryGetValue("name", out object? rawName) && rawName is string name &&
                         name.Equals(projectName, StringComparison.Ordinal)));
                }
                else if (rawProjects is TomlTable single)
                {
                    project = single;
                }
            }

            if (project is null ||
                !project.TryGetValue("agent", out object? rawAgent) || rawAgent is not TomlTable agent ||
                !agent.TryGetValue("options", out object? rawOptions) || rawOptions is not TomlTable options ||
                !options.TryGetValue("work_dir", out object? rawWorkDir) || rawWorkDir is not string workDir ||
                string.IsNullOrWhiteSpace(workDir))
            {
                return null;
            }

            return workDir;
        }
        catch (Exception)
        {
            return null;
        }
    }

    /// <summary>
    /// 读回当前 agent 真正可用的全局 provider 名称,供 provider_refs 引用。
    /// TOML 由 Tomlyn 结构化解析;重复名称遵循 cc-connect 的 last-wins 语义。
    /// </summary>
    public static IReadOnlyList<string> ReadGlobalProviderNames(string existingToml, string agentType = "")
    {
        CcConnectProviderCatalog catalog = CcConnectProviderCatalog.Parse(existingToml);
        return catalog.Providers
            .Where(provider => agentType.Length == 0 || provider.SupportsAgent(agentType))
            .Select(provider => provider.Name)
            .ToArray();
    }

    /// <summary>
    /// cc-connect 的默认 <c>model</c> 与模型菜单是两套字段。Provider 只有标量 model、
    /// 没有 <c>[[providers.models]]</c> 时,Claude Code/Codex 都可能回退到内置菜单,
    /// 让用户误以为自定义服务商没有生效。这里只给当前项目实际引用的 provider 补候选:
    /// 一般 provider 补有效默认 model;只有官方 OpenAI 端点的当前 GPT-5.6 家族
    /// 才额外补官方推荐的 Sol/Terra/Luna。第三方 relay 不推断未声明能力。
    /// </summary>
    private const string GeneratedModelListMarker =
        "# Generated by AI Resume from the provider effective default model.";
    private const string GeneratedModelListBegin = "# AI Resume generated model list: begin";
    private const string GeneratedModelListEnd = "# AI Resume generated model list: end";
    private const string ManagedAliasPrefix = "[AI Resume] ";

    private static readonly CcConnectProviderModel[] CurrentCodexModels =
    {
        new("gpt-5.6-sol", ManagedAliasPrefix + "GPT-5.6 Sol（旗舰）"),
        new("gpt-5.6-terra", ManagedAliasPrefix + "GPT-5.6 Terra（均衡）"),
        new("gpt-5.6-luna", ManagedAliasPrefix + "GPT-5.6 Luna（经济高吞吐）"),
    };

    internal static string EnsureSelectableProviderModels(string preservedToml, CcConnectConfig config)
    {
        if (string.IsNullOrWhiteSpace(preservedToml))
        {
            return preservedToml;
        }

        string withoutGenerated = RemoveGeneratedModelLists(preservedToml);
        CcConnectProviderCatalog catalog = CcConnectProviderCatalog.Parse(withoutGenerated);
        HashSet<string> managedCodexProviders = FindManagedCodexProviders(catalog, config);
        if (managedCodexProviders.Count > 0)
        {
            // 上游部分 CRUD 会经 TOML decode/encode 重写配置并剥掉注释 marker,
            // 但 alias 是模型表的正式语义字段。
            // 只重建每一项都带明确 [AI Resume] 前缀的目录;无 alias 的单项表
            // 无法证明所有权,必须视为用户配置原样保留。
            withoutGenerated = RemoveManagedCodexModelLists(withoutGenerated, managedCodexProviders);
            catalog = CcConnectProviderCatalog.Parse(withoutGenerated);
        }
        var required = new Dictionary<string, Dictionary<string, IReadOnlyList<CcConnectProviderModel>>>(
            StringComparer.Ordinal);
        foreach (CcConnectProject project in config.Projects)
        {
            foreach (string providerName in project.ProviderRefs ?? Array.Empty<string>())
            {
                CcConnectProviderDescriptor? provider = catalog.Find(providerName);
                if (provider is null ||
                    provider.AgentModelLists.ContainsKey(project.Agent) ||
                    provider.HasModelsDefinition)
                {
                    continue;
                }

                string model = provider.EffectiveModel(project.Agent);
                if (model.Length == 0)
                {
                    continue;
                }

                if (!required.TryGetValue(
                        provider.Name,
                        out Dictionary<string, IReadOnlyList<CcConnectProviderModel>>? agents))
                {
                    agents = new Dictionary<string, IReadOnlyList<CcConnectProviderModel>>(StringComparer.Ordinal);
                    required[provider.Name] = agents;
                }

                agents[project.Agent] = GeneratedModels(provider, project.Agent, model);
            }
        }

        if (required.Count == 0)
        {
            return withoutGenerated.Trim();
        }

        string[] lines = withoutGenerated.Replace("\r\n", "\n").Split('\n');
        List<ProviderTextBlock> blocks = FindProviderBlocks(lines);
        var lastByName = blocks
            .Where(block => block.Name.Length > 0)
            .GroupBy(block => block.Name, StringComparer.Ordinal)
            .ToDictionary(group => group.Key, group => group.Last(), StringComparer.Ordinal);
        var insertions = new Dictionary<int, List<string>>();
        foreach ((string providerName, Dictionary<string, IReadOnlyList<CcConnectProviderModel>> agents) in required)
        {
            if (!lastByName.TryGetValue(providerName, out ProviderTextBlock? block) || block is null)
            {
                continue;
            }
            if (block.HasInlineAgentModelLists)
            {
                continue;
            }

            var generated = new List<string> { string.Empty };
            foreach ((string agent, IReadOnlyList<CcConnectProviderModel> models) in
                     agents.OrderBy(item => item.Key, StringComparer.Ordinal))
            {
                foreach (CcConnectProviderModel model in models)
                {
                    generated.Add("  " + GeneratedModelListBegin);
                    generated.Add($"  [[providers.agent_model_lists.{agent}]]");
                    generated.Add("    model = " + TomlString(model.Model));
                    if (model.Alias.Length > 0)
                    {
                        generated.Add("    alias = " + TomlString(model.Alias));
                    }
                    generated.Add("  " + GeneratedModelListEnd);
                }
            }

            insertions[block.End] = generated;
        }

        var output = new List<string>(lines.Length + insertions.Values.Sum(items => items.Count));
        for (int i = 0; i <= lines.Length; i++)
        {
            if (insertions.TryGetValue(i, out List<string>? generated))
            {
                output.AddRange(generated);
            }

            if (i < lines.Length)
            {
                output.Add(lines[i]);
            }
        }

        return string.Join(Environment.NewLine, output).Trim();
    }

    private static HashSet<string> FindManagedCodexProviders(
        CcConnectProviderCatalog catalog,
        CcConnectConfig config)
    {
        var referenced = config.Projects
            .Where(project => project.Agent.Equals("codex", StringComparison.Ordinal))
            .SelectMany(project => project.ProviderRefs ?? Array.Empty<string>())
            .ToHashSet(StringComparer.Ordinal);
        return catalog.Providers
            .Where(provider => referenced.Contains(provider.Name))
            .Where(provider => provider.AgentModelLists.TryGetValue(
                "codex", out IReadOnlyList<CcConnectProviderModel>? models) &&
                models.Count > 0 &&
                models.All(model => model.Alias.StartsWith(ManagedAliasPrefix, StringComparison.Ordinal)))
            .Select(provider => provider.Name)
            .ToHashSet(StringComparer.Ordinal);
    }

    private static string RemoveManagedCodexModelLists(string toml, HashSet<string> providerNames)
    {
        string[] lines = toml.Replace("\r\n", "\n").Split('\n');
        var remove = new HashSet<int>();
        foreach (ProviderTextBlock block in FindProviderBlocks(lines))
        {
            if (!providerNames.Contains(block.Name))
            {
                continue;
            }

            for (int i = block.Start + 1; i < block.End; i++)
            {
                if (!HeaderEquals(lines[i], array: true, "providers", "agent_model_lists", "codex"))
                {
                    continue;
                }

                int end = i + 1;
                while (end < block.End && !lines[end].TrimStart().StartsWith('['))
                {
                    end++;
                }

                for (int line = i; line < end; line++)
                {
                    remove.Add(line);
                }
                i = end - 1;
            }
        }

        return string.Join(Environment.NewLine,
            lines.Where((_, index) => !remove.Contains(index))).Trim();
    }

    private static IReadOnlyList<CcConnectProviderModel> GeneratedModels(
        CcConnectProviderDescriptor provider,
        string agent,
        string effectiveModel)
    {
        if (!agent.Equals("codex", StringComparison.Ordinal) ||
            !IsCurrentCodexFamily(effectiveModel))
        {
            return new[] { new CcConnectProviderModel(effectiveModel, ManagedAliasPrefix + effectiveModel) };
        }

        var result = new List<CcConnectProviderModel>
        {
            new(effectiveModel,
                effectiveModel.Equals("gpt-5.6", StringComparison.Ordinal)
                    ? ManagedAliasPrefix + "GPT-5.6（当前默认）"
                    : CurrentCodexModels.First(model => model.Model.Equals(
                        effectiveModel, StringComparison.Ordinal)).Alias),
        };
        // 官方模型目录只能证明 OpenAI API 的能力。第三方 relay 即使默认名叫
        // gpt-5.6,也不等于支持 Sol/Terra/Luna 的独立 slug;不得替它宣称能力。
        if (!IsOfficialOpenAiEndpoint(provider))
        {
            return result;
        }

        foreach (CcConnectProviderModel model in CurrentCodexModels)
        {
            if (!result.Any(existing => existing.Model.Equals(model.Model, StringComparison.Ordinal)))
            {
                result.Add(model);
            }
        }

        return result;
    }

    private static bool IsCurrentCodexFamily(string model) =>
        model.Equals("gpt-5.6", StringComparison.Ordinal) ||
        CurrentCodexModels.Any(candidate => candidate.Model.Equals(model, StringComparison.Ordinal));

    private static bool IsOfficialOpenAiEndpoint(CcConnectProviderDescriptor provider)
    {
        string endpoint = provider.Endpoints.TryGetValue("codex", out string? overrideEndpoint) &&
                          overrideEndpoint.Length > 0
            ? overrideEndpoint
            : provider.BaseUrl;
        if (endpoint.Length == 0)
        {
            return true;
        }

        return Uri.TryCreate(endpoint, UriKind.Absolute, out Uri? uri) &&
               uri.Host.Equals("api.openai.com", StringComparison.OrdinalIgnoreCase);
    }

    private static string RemoveGeneratedModelLists(string toml)
    {
        string[] lines = toml.Replace("\r\n", "\n").Split('\n');
        var output = new List<string>(lines.Length);
        for (int i = 0; i < lines.Length; i++)
        {
            if (lines[i].Trim().Equals(GeneratedModelListBegin, StringComparison.Ordinal))
            {
                int end = i + 3;
                if (i + 3 < lines.Length &&
                    HeaderStartsWithPath(lines[i + 1], "providers", "agent_model_lists") &&
                    lines[i + 2].Trim().StartsWith("model =", StringComparison.Ordinal) &&
                    lines[i + 3].TrimStart().StartsWith("alias =", StringComparison.Ordinal))
                {
                    end = i + 4;
                }

                if (end < lines.Length &&
                    lines[end].Trim().Equals(GeneratedModelListEnd, StringComparison.Ordinal))
                {
                    // 生成块前的单个空行也是本生成器加的。若不一并收回,
                    // 每次重建多模型列表都会多积一行,破坏确定性字节输出。
                    if (output.Count > 0 && string.IsNullOrWhiteSpace(output[^1]))
                    {
                        output.RemoveAt(output.Count - 1);
                    }
                    i = end;
                    continue;
                }

                output.Add(lines[i]);
                continue;
            }

            if (!lines[i].Trim().Equals(GeneratedModelListMarker, StringComparison.Ordinal))
            {
                output.Add(lines[i]);
                continue;
            }

            int header = i + 1;
            if (header >= lines.Length ||
                !HeaderStartsWithPath(lines[header], "providers", "agent_model_lists"))
            {
                output.Add(lines[i]);
                continue;
            }

            i = header;
            while (i + 1 < lines.Length && !lines[i + 1].TrimStart().StartsWith('['))
            {
                i++;
            }
        }

        return string.Join(Environment.NewLine, output);
    }

    private static List<ProviderTextBlock> FindProviderBlocks(string[] lines)
    {
        var result = new List<ProviderTextBlock>();
        int start = -1;
        for (int i = 0; i <= lines.Length; i++)
        {
            string trimmed = i < lines.Length ? lines[i].Trim() : string.Empty;
            bool providerStart = i < lines.Length && HeaderEquals(lines[i], array: true, "providers");
            bool foreignTable = i == lines.Length ||
                (trimmed.StartsWith('[') &&
                 !HeaderStartsWithPath(lines[i], "providers") &&
                 !providerStart);

            if (start >= 0 && (providerStart || foreignTable))
            {
                string blockText = string.Join("\n", lines[start..i]);
                string name = string.Empty;
                try
                {
                    name = CcConnectProviderCatalog.Parse(blockText).Providers.LastOrDefault()?.Name ?? string.Empty;
                }
                catch (Exception)
                {
                    // Upstream validation will report malformed TOML; model supplementation stays no-op.
                }

                bool hasInlineAgentModelLists = blockText
                    .Split('\n')
                    .Any(line => AssignmentKeyEquals(line, "agent_model_lists"));
                result.Add(new ProviderTextBlock(start, i, name, hasInlineAgentModelLists));
                start = -1;
            }

            if (providerStart)
            {
                start = i;
            }
        }

        return result;
    }

    private sealed record ProviderTextBlock(int Start, int End, string Name, bool HasInlineAgentModelLists);

    private static string RenderCore(
        CcConnectConfig config,
        bool redact,
        ProjectPreservation? preservation = null)
    {
        CcConnectConfig.Validate(config);
        preservation ??= ProjectPreservation.Empty;
        var sb = new StringBuilder();
        sb.Append("# Generated by AiResume.Wrapper (S6-A). Deterministic; do not edit by hand.")
          .Append(Environment.NewLine);

        // 形状必须与 cc-connect 的 config.AgentConfig 一致:agent 是**表**不是字符串,
        // work_dir / mode 落在 projects.agent.options 里。
        //
        // 2026-08-06 生产切换实测踩到:原实现写成
        //   agent = "claudecode" / work_dir = "..." / mode = "..."(全在 [[projects]] 顶层),
        // cc-connect 直接拒绝加载——
        //   parse config: type mismatch for config.AgentConfig: expected table but found string。
        // 这个错误从 S6-A 起就存在,而当时的测试只断言了我们自己臆想的输出格式,
        // 从未拿真的 cc-connect 跑过一次,所以一直没暴露。**契约要以对方的解析器为准。**
        for (int projectIndex = 0; projectIndex < config.Projects.Count; projectIndex++)
        {
            CcConnectProject project = config.Projects[projectIndex];
            ProjectPreservation current = projectIndex == 0 ? preservation : ProjectPreservation.Empty;
            sb.Append(Environment.NewLine);
            sb.Append("[[projects]]").Append(Environment.NewLine);
            sb.Append("  name = ").Append(TomlString(project.Name)).Append(Environment.NewLine);
            if (!string.IsNullOrWhiteSpace(project.AdminFrom))
            {
                // **必须在这一层**:上游文档明确写了放进 platforms.options 会被忽略。
                sb.Append("  admin_from = ").Append(TomlString(project.AdminFrom)).Append(Environment.NewLine);
            }
            AppendPreservedLines(sb, current.ProjectLines);

            sb.Append(Environment.NewLine);
            sb.Append("  [projects.agent]").Append(Environment.NewLine);
            sb.Append("    type = ").Append(TomlString(project.Agent)).Append(Environment.NewLine);
            // 引用顶层 [[providers]] 里的全局服务商。不写这一行,项目就用不到它们
            // ——2026-08-06 实测:`/provider switch deepseek` 报「未找到」正是缺这个。
            if (project.ProviderRefs is { Count: > 0 } refs)
            {
                sb.Append("    provider_refs = [")
                  .Append(string.Join(", ", refs.Select(TomlString)))
                  .Append(']').Append(Environment.NewLine);
            }
            AppendPreservedLines(sb, current.AgentLines);
            sb.Append(Environment.NewLine);
            sb.Append("    [projects.agent.options]").Append(Environment.NewLine);
            sb.Append("      mode = ").Append(TomlString(project.Mode)).Append(Environment.NewLine);
            sb.Append("      work_dir = ").Append(TomlString(project.WorkDir)).Append(Environment.NewLine);
            if (project.SelectedProvider.Length > 0)
            {
                sb.Append("      provider = ").Append(TomlString(project.SelectedProvider)).Append(Environment.NewLine);
            }
            if (project.SelectedModel.Length > 0)
            {
                sb.Append("      model = ").Append(TomlString(project.SelectedModel)).Append(Environment.NewLine);
            }
            AppendPreservedLines(sb, current.AgentOptionLines);

            sb.Append(Environment.NewLine);
            sb.Append("      [projects.agent.options.env]").Append(Environment.NewLine);
            sb.Append("        AI_RESUME_INTERNAL_RUN = \"1\"").Append(Environment.NewLine);
            foreach ((string key, string value) in current.AgentEnvironment)
            {
                sb.Append("        ").Append(TomlString(key)).Append(" = ")
                  .Append(redact ? "\"[REDACTED]\"" : TomlString(value))
                  .Append(Environment.NewLine);
            }

            foreach (string block in current.AdditionalBlocks)
            {
                sb.Append(Environment.NewLine);
                sb.Append(block).Append(Environment.NewLine);
            }

            sb.Append(Environment.NewLine);
            sb.Append("  [[projects.platforms]]").Append(Environment.NewLine);
            sb.Append("    type = \"feishu\"").Append(Environment.NewLine);
            sb.Append(Environment.NewLine);
            sb.Append("    [projects.platforms.options]").Append(Environment.NewLine);
            sb.Append("      app_id = ").Append(TomlString(config.Feishu.AppId)).Append(Environment.NewLine);
            sb.Append("      app_secret = ")
              .Append(redact ? "\"[REDACTED]\"" : TomlString(config.Feishu.AppSecret))
              .Append(Environment.NewLine);
            sb.Append("      allow_from = ").Append(TomlString(config.Feishu.AllowFrom)).Append(Environment.NewLine);

            // 非飞书平台原样保留:微信等平台是用户扫码绑定的资产,整块重写会把它抹掉。
            // 追加在飞书块之后,同属于该项目。缩进保持原样,块之间空一行。
            // 注意:脱敏输出绝不能包含这些块——微信平台的 options 里有 bearer token,
            // 属于凭据,不得回显到界面或日志。
            if (!redact && current.ForeignPlatforms.Count > 0)
            {
                foreach (string block in current.ForeignPlatforms)
                {
                    sb.Append(Environment.NewLine);
                    sb.Append(block).Append(Environment.NewLine);
                }
            }
        }

        // 脱敏输出末尾追加一行注释,说明有多少个非飞书平台被保留但未回显。
        // 这样日志/界面能看出"有东西被藏起来了",又不泄露凭据内容。
        if (redact && preservation.ForeignPlatforms.Count > 0)
        {
            sb.Append(Environment.NewLine);
            sb.Append("# 另保留 ").Append(preservation.ForeignPlatforms.Count)
              .Append(" 个非飞书平台(内容含凭据,不在此回显)").Append(Environment.NewLine);
        }

        return sb.ToString();
    }

    private static void AppendPreservedLines(StringBuilder sb, IReadOnlyList<string> lines)
    {
        if (lines.Count == 0)
        {
            return;
        }

        foreach (string line in lines)
        {
            sb.Append(line).Append(Environment.NewLine);
        }
    }

    /// <summary>TOML 基础字符串转义(反斜杠/双引号/控制字符)。</summary>
    private static string TomlString(string value)
    {
        var sb = new StringBuilder("\"");
        foreach (char c in value)
        {
            switch (c)
            {
                case '\\':
                    sb.Append("\\\\");
                    break;
                case '"':
                    sb.Append("\\\"");
                    break;
                case '\n':
                    sb.Append("\\n");
                    break;
                case '\r':
                    sb.Append("\\r");
                    break;
                case '\t':
                    sb.Append("\\t");
                    break;
                default:
                    if (char.IsControl(c))
                    {
                        sb.Append("\\u").Append(((int)c).ToString("X4"));
                    }
                    else
                    {
                        sb.Append(c);
                    }

                    break;
            }
        }

        return sb.Append('"').ToString();
    }
}
