using System.Text;

namespace AiResume.Wrapper;

/// <summary>
/// S6-A cc-connect 配置契约模型(与 S4-A 试点实证形状一致):
/// 1 个 feishu 平台 + N 个 agent 项目;凭据只经参数注入并写入仓库外路径,
/// 模型本身不提供任何默认凭据。
/// </summary>
/// <summary>
/// 飞书平台选项。<paramref name="AllowFrom"/> 是**逗号分隔的 open_id 字符串**
/// (不是数组),<c>"*"</c> 表示放行所有人。
///
/// **不允许为空**:cc-connect 在未设置时会打印
/// 「allow_from is not set — all users are permitted」并放行所有人,
/// 而现役系统是靠 feishuAuthOpenIds 锁死的。空值等于把 12 个项目目录的
/// 读写权限开放给任何能给机器人发消息的人(2026-08-06 切换时实测到,暴露约 90 秒)。
/// </summary>
public sealed record CcConnectPlatformOptions(string AppId, string AppSecret, string AllowFrom);

/// <summary>
/// cc-connect 项目定义([[projects]]);agent 取值如 claudecode/codex。
///
/// <paramref name="AdminFrom"/> 控制 /shell、/dir 等特权命令,同样是逗号分隔字符串。
/// **必须写在 [[projects]] 这一层**——上游文档明确警告:放进
/// [projects.platforms.options] 会被静默忽略。
/// </summary>
public sealed record CcConnectProject(
    string Name, string Agent, string WorkDir, string Mode = "default", string AdminFrom = "",
    IReadOnlyList<string>? ProviderRefs = null);

/// <summary>cc-connect 整体配置输入;Render 输出确定性 TOML(相同输入 → 相同字节)。</summary>
public sealed record CcConnectConfig(IReadOnlyList<CcConnectProject> Projects, CcConnectPlatformOptions Feishu)
{
    public static void Validate(CcConnectConfig config)
    {
        ArgumentNullException.ThrowIfNull(config);
        ArgumentNullException.ThrowIfNull(config.Feishu);
        if (string.IsNullOrWhiteSpace(config.Feishu.AppId))
        {
            throw new ArgumentException("飞书 app_id 不得为空。", nameof(config));
        }

        if (string.IsNullOrWhiteSpace(config.Feishu.AppSecret))
        {
            throw new ArgumentException("飞书 app_secret 不得为空。", nameof(config));
        }

        // fail-closed:空 allow_from 会让 cc-connect 放行所有人。宁可拒绝生成配置,
        // 也不产出一份"任何人都能驱动 Claude Code 改你项目"的配置。
        if (string.IsNullOrWhiteSpace(config.Feishu.AllowFrom))
        {
            throw new ArgumentException(
                "allow_from 不得为空:cc-connect 未设置该项时会放行所有飞书用户。", nameof(config));
        }

        if (config.Projects.Count == 0)
        {
            throw new ArgumentException("至少需要 1 个项目。", nameof(config));
        }

        foreach (CcConnectProject project in config.Projects)
        {
            if (string.IsNullOrWhiteSpace(project.Name) || string.IsNullOrWhiteSpace(project.WorkDir))
            {
                throw new ArgumentException("项目 name/work_dir 不得为空。", nameof(config));
            }
        }
    }
}

/// <summary>
/// S6-A cc-connect config.toml 确定性生成器:
/// - Render 只依赖输入(无时间戳/随机量),相同输入产出相同字节(便于对账与测试);
/// - Write 落仓库外路径:临时文件 + 原子替换(File.Move overwrite),
///   任何时刻磁盘上要么旧完整内容要么新完整内容(对齐现役 config.json 写纪律);
/// - RenderSanitized 供日志/测试展示,凭据一律 [REDACTED],实值零出现。
/// </summary>
public static class CcConnectConfigGenerator
{
    /// <summary>
    /// 生成标记行。保留既有内容时要按它剔除上一轮写入的那行,否则每次生成都会多一行,
    /// 逐轮累积成一叠重复注释。
    /// </summary>
    private const string GeneratedMarker = "# Generated by AiResume.Wrapper";

    /// <summary>生成确定性 TOML 文本(含真实凭据;只允许写仓库外路径,不得进日志)。</summary>
    public static string Render(CcConnectConfig config) => RenderCore(config, redact: false);

    /// <summary>生成脱敏 TOML 文本(app_secret/敏感值置换 [REDACTED]),供日志与断言展示。</summary>
    public static string RenderSanitized(CcConnectConfig config) => RenderCore(config, redact: true);

    /// <summary>
    /// 带「保留了几个非飞书平台」计数的脱敏渲染。
    ///
    /// 计数必须露出来:用户点「生成 cc-connect 配置」后只看得到这份回显,
    /// 如果扫码绑好的微信平台被保留了却只字不提,沉默会被读成"它没了"——
    /// 于是又去扫一次码。**保留块本身绝不回显**:它的 options 里有 bearer token。
    /// </summary>
    public static string RenderSanitized(CcConnectConfig config, int foreignPlatformCount)
        => RenderCore(config, redact: true,
            foreignPlatformCount > 0 ? new string[foreignPlatformCount] : null);

    /// <summary>
    /// 原子写入仓库外路径(临时文件 + 原子替换);路径与内容均不入仓库。
    ///
    /// **保留我们不管的段落**:目标文件已存在时,原样保留除 <c>[[projects]]</c> 之外的
    /// 全部内容——`[management]`(9820 端口的 Web 管理台)、`[log]`、`[speech]`、`[tts]`、
    /// webhook、hooks、顶层的 data_dir/language 等等。
    ///
    /// 2026-08-06 切换时踩到:本方法原本整份覆盖,只写 [[projects]],
    /// 把用户已启用的 `[management]` 一并抹掉,admin 页 http://localhost:9820 直接打不开。
    /// **这份配置不归我们独占**——我们只拥有项目清单这一部分,其余是 cc-connect 与用户的。
    ///
    /// 同理,`cc-connect weixin setup` 扫码绑定的微信平台也属于用户资产:
    /// 整块重写 [[projects]] 时若把它丢掉,用户下次扫码绑定就白做了。
    /// 所以这里把非飞书平台块原样抽出来,追加到生成的飞书块之后。
    /// </summary>
    public static void Write(string path, CcConnectConfig config)
    {
        ArgumentException.ThrowIfNullOrEmpty(path);
        CcConnectConfig.Validate(config);
        string? directory = Path.GetDirectoryName(path);
        if (!string.IsNullOrEmpty(directory))
        {
            Directory.CreateDirectory(directory);
        }

        string preserved = string.Empty;
        IReadOnlyList<string> foreignPlatforms = Array.Empty<string>();
        if (File.Exists(path))
        {
            try
            {
                string existing = File.ReadAllText(path);
                preserved = ExtractNonProjectSections(existing);
                foreignPlatforms = ExtractForeignPlatforms(existing);
            }
            catch (IOException)
            {
                // 读不到旧文件:退化成只写项目段。宁可少保留,也不要因此写不出配置。
                preserved = string.Empty;
                foreignPlatforms = Array.Empty<string>();
            }
        }

        string content = RenderCore(config, redact: false, foreignPlatforms);
        if (!string.IsNullOrWhiteSpace(preserved))
        {
            content = preserved.TrimEnd() + Environment.NewLine + Environment.NewLine + content;
        }

        string tmp = path + ".tmp-" + Guid.NewGuid().ToString("N");
        try
        {
            File.WriteAllText(tmp, content, new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
            File.Move(tmp, path, overwrite: true);
        }
        finally
        {
            if (File.Exists(tmp))
            {
                try
                {
                    File.Delete(tmp);
                }
                catch
                {
                    // 替换已完成;残留 tmp 清理失败不抛出。
                }
            }
        }
    }

    /// <summary>
    /// 从既有 TOML 中剔除全部 <c>[[projects]]</c> 及其子表(<c>[projects.*]</c>),
    /// 其余内容原样返回。
    ///
    /// 只做行级切分而不做完整 TOML 解析:我们要的是"原样保留",一旦解析再序列化,
    /// 用户的注释、段落顺序和格式就全没了——而这份文件里的注释正是 cc-connect
    /// 自带的使用说明。同理也剔除我们自己上一轮写入的生成标记行,避免逐轮累积。
    /// </summary>
    internal static string ExtractNonProjectSections(string existingToml)
    {
        var kept = new List<string>();
        bool inProjectBlock = false;

        foreach (string line in existingToml.Replace("\r\n", "\n").Split('\n'))
        {
            string trimmed = line.TrimStart();

            if (trimmed.StartsWith('['))
            {
                // 顶层表头出现:重新判定是否落在 projects 区域内。
                inProjectBlock =
                    trimmed.StartsWith("[[projects]]", StringComparison.Ordinal) ||
                    trimmed.StartsWith("[projects.", StringComparison.Ordinal) ||
                    trimmed.StartsWith("[[projects.", StringComparison.Ordinal);
            }

            if (inProjectBlock)
            {
                continue;
            }

            if (trimmed.StartsWith(GeneratedMarker, StringComparison.Ordinal))
            {
                continue;
            }

            kept.Add(line);
        }

        return string.Join(Environment.NewLine, kept).Trim();
    }

    /// <summary>
    /// 从既有 config.toml 里原样抽出**非 feishu** 的 [[projects.platforms]] 块。
    /// 逐块返回原始文本(含表头行),块之间不含额外空行。没有则返回空列表。
    ///
    /// 为什么必须逐行扫描而不是跨行正则:真实文件里 [[projects.platforms]] 与
    /// [projects.platforms.options] 等表头互相嵌套,跨行匹配会越过表边界,
    /// 把别的表的内容误并进来。逐行扫描天然尊重表边界。
    ///
    /// 为什么未知类型也保留:取不到 type 时宁可多留不可丢——丢了等于用户白扫一次码。
    /// </summary>
    public static IReadOnlyList<string> ExtractForeignPlatforms(string existingToml)
    {
        if (string.IsNullOrEmpty(existingToml))
        {
            return Array.Empty<string>();
        }

        var result = new List<string>();
        var currentBlock = new List<string>();
        bool inBlock = false;
        string? platformType = null;

        void FlushBlock()
        {
            if (!inBlock)
            {
                return;
            }

            // 去掉块尾的连续空行。
            while (currentBlock.Count > 0 && string.IsNullOrWhiteSpace(currentBlock[currentBlock.Count - 1]))
            {
                currentBlock.RemoveAt(currentBlock.Count - 1);
            }

            // 类型等于 feishu(忽略大小写)的块丢弃:飞书那块由生成器自己产出。
            // 取不到类型视为未知类型,一并保留。
            if (currentBlock.Count > 0 &&
                !string.Equals(platformType, "feishu", StringComparison.OrdinalIgnoreCase))
            {
                result.Add(string.Join(Environment.NewLine, currentBlock));
            }

            currentBlock.Clear();
            platformType = null;
            inBlock = false;
        }

        foreach (string line in existingToml.Replace("\r\n", "\n").Split('\n'))
        {
            string trimmedStart = line.TrimStart();
            string trimmed = line.Trim();

            if (trimmedStart.StartsWith("[[projects.platforms]]", StringComparison.Ordinal))
            {
                // 新块开始:先冲刷上一个块。
                FlushBlock();
                inBlock = true;
                currentBlock.Add(line);
                continue;
            }

            if (inBlock)
            {
                // 块的结束:下一个去掉行首空白后以 "[[" 开头的行,
                // 或者下一个不以 "[projects.platforms" 开头的 "[" 表头行。
                if (trimmedStart.StartsWith("[[", StringComparison.Ordinal) ||
                    (trimmedStart.StartsWith('[') &&
                     !trimmedStart.StartsWith("[projects.platforms", StringComparison.Ordinal)))
                {
                    FlushBlock();
                    // 这个表头行不属于当前块,交给后续逻辑处理(但这里不重新进入块)。
                    continue;
                }

                // 块内查找类型:去掉空白后以 "type" 开头且含 "=" 的行,
                // 取第一个双引号对之间的值作为平台类型。
                if (platformType is null &&
                    trimmed.StartsWith("type", StringComparison.Ordinal) &&
                    trimmed.Contains('='))
                {
                    int q1 = trimmed.IndexOf('"');
                    int q2 = q1 >= 0 ? trimmed.IndexOf('"', q1 + 1) : -1;
                    if (q1 >= 0 && q2 > q1)
                    {
                        platformType = trimmed.Substring(q1 + 1, q2 - q1 - 1);
                    }
                }

                currentBlock.Add(line);
            }
        }

        // 文件结束:冲刷最后一个块。
        FlushBlock();
        return result;
    }

    /// <summary>
    /// 从既有 config.toml 里读回 [projects.agent.options] 的 work_dir。
    /// 读不到返回 null。
    ///
    /// 只认 [projects.agent.options] 这张表下面的 work_dir;文件其它位置出现的
    /// work_dir 一律忽略。实现是逐行扫描:先定位到 [projects.agent.options] 行,
    /// 然后在遇到下一个表头行之前查找 work_dir 赋值行。
    ///
    /// **不可写成跨行正则**:真实文件里 [[projects.platforms]] 等表头夹在中间,
    /// 跨行匹配会越过表边界读到别的表的值。
    /// </summary>
    public static string? TryReadExistingWorkDir(string existingToml)
    {
        if (string.IsNullOrEmpty(existingToml))
        {
            return null;
        }

        bool inAgentOptions = false;
        foreach (string line in existingToml.Replace("\r\n", "\n").Split('\n'))
        {
            string trimmed = line.Trim();
            if (trimmed.StartsWith('['))
            {
                // 表头行:重新判定是否落在 [projects.agent.options] 区域内。
                inAgentOptions = trimmed.StartsWith("[projects.agent.options]", StringComparison.Ordinal);
                continue;
            }

            if (!inAgentOptions)
            {
                continue;
            }

            if (trimmed.StartsWith("work_dir", StringComparison.Ordinal))
            {
                int eq = trimmed.IndexOf('=');
                if (eq < 0)
                {
                    return null;
                }

                string value = trimmed.Substring(eq + 1).Trim();
                if (value.Length < 2 || value[0] != '"' || value[value.Length - 1] != '"')
                {
                    return null;
                }

                string inner = value.Substring(1, value.Length - 2);
                if (string.IsNullOrWhiteSpace(inner))
                {
                    return null;
                }

                // 只处理 \\ → \ 与 \" → " 两种转义,其它原样保留。
                var sb = new StringBuilder(inner.Length);
                for (int i = 0; i < inner.Length; i++)
                {
                    if (inner[i] == '\\' && i + 1 < inner.Length)
                    {
                        char next = inner[i + 1];
                        if (next == '\\')
                        {
                            sb.Append('\\');
                            i++;
                            continue;
                        }

                        if (next == '"')
                        {
                            sb.Append('"');
                            i++;
                            continue;
                        }
                    }

                    sb.Append(inner[i]);
                }

                return sb.ToString();
            }
        }

        return null;
    }

    /// <summary>读回顶层 <c>[[providers]]</c> 的名字,供 provider_refs 引用。</summary>
    public static IReadOnlyList<string> ReadGlobalProviderNames(string existingToml, string agentType = "")
    {
        var names = new List<string>();
        bool inProviders = false;
        string? pendingName = null;
        bool pendingApplies = true;

        void Flush()
        {
            if (pendingName is not null && pendingApplies)
            {
                names.Add(pendingName);
            }

            pendingName = null;
            pendingApplies = true;
        }

        foreach (string line in existingToml.Replace("\r\n", "\n").Split('\n'))
        {
            string t = line.Trim();
            if (t.StartsWith('['))
            {
                Flush();
                inProviders = t.StartsWith("[[providers]]", StringComparison.Ordinal);
                continue;
            }

            if (!inProviders)
            {
                continue;
            }

            if (t.StartsWith("name", StringComparison.Ordinal))
            {
                int q1 = t.IndexOf('"');
                int q2 = q1 >= 0 ? t.IndexOf('"', q1 + 1) : -1;
                if (q1 >= 0 && q2 > q1)
                {
                    pendingName = t.Substring(q1 + 1, q2 - q1 - 1);
                }
            }
            else if (t.StartsWith("agent_types", StringComparison.Ordinal) && agentType.Length > 0)
            {
                // 服务商可以声明只适用于某些 agent(如 chatpt-月付 是 agent_types = ["codex"])。
                // 从 claudecode 项目去 provider_refs 引用一个 codex-only 的服务商,
                // 在飞书里表现为 `/provider switch` 列得出来却切不过去。
                // 没声明 agent_types 视为通用,照引。
                pendingApplies = t.Contains('"' + agentType + '"', StringComparison.Ordinal);
            }
        }

        Flush();
        return names;
    }

    private static string RenderCore(
        CcConnectConfig config,
        bool redact,
        IReadOnlyList<string>? foreignPlatforms = null)
    {
        CcConnectConfig.Validate(config);
        var sb = new StringBuilder();
        sb.Append("# Generated by AiResume.Wrapper (S6-A). Deterministic; do not edit by hand.")
          .Append(Environment.NewLine);

        // 形状必须与 cc-connect 的 config.AgentConfig 一致:agent 是**表**不是字符串,
        // work_dir / mode 落在 projects.agent.options 里。
        //
        // 2026-08-06 生产切换实测踩到:原实现写成
        //   agent = "claudecode" / work_dir = "..." / mode = "..."(全在 [[projects]] 顶层),
        // cc-connect 直接拒绝加载——
        //   parse config: type mismatch for config.AgentConfig: expected table but found string。
        // 这个错误从 S6-A 起就存在,而当时的测试只断言了我们自己臆想的输出格式,
        // 从未拿真的 cc-connect 跑过一次,所以一直没暴露。**契约要以对方的解析器为准。**
        foreach (CcConnectProject project in config.Projects)
        {
            sb.Append(Environment.NewLine);
            sb.Append("[[projects]]").Append(Environment.NewLine);
            sb.Append("  name = ").Append(TomlString(project.Name)).Append(Environment.NewLine);
            if (!string.IsNullOrWhiteSpace(project.AdminFrom))
            {
                // **必须在这一层**:上游文档明确写了放进 platforms.options 会被忽略。
                sb.Append("  admin_from = ").Append(TomlString(project.AdminFrom)).Append(Environment.NewLine);
            }

            sb.Append(Environment.NewLine);
            sb.Append("  [projects.agent]").Append(Environment.NewLine);
            sb.Append("    type = ").Append(TomlString(project.Agent)).Append(Environment.NewLine);
            // 引用顶层 [[providers]] 里的全局服务商。不写这一行,项目就用不到它们
            // ——2026-08-06 实测:`/provider switch deepseek` 报「未找到」正是缺这个。
            if (project.ProviderRefs is { Count: > 0 } refs)
            {
                sb.Append("    provider_refs = [")
                  .Append(string.Join(", ", refs.Select(TomlString)))
                  .Append(']').Append(Environment.NewLine);
            }
            sb.Append(Environment.NewLine);
            sb.Append("    [projects.agent.options]").Append(Environment.NewLine);
            sb.Append("      mode = ").Append(TomlString(project.Mode)).Append(Environment.NewLine);
            sb.Append("      work_dir = ").Append(TomlString(project.WorkDir)).Append(Environment.NewLine);
            sb.Append(Environment.NewLine);
            sb.Append("  [[projects.platforms]]").Append(Environment.NewLine);
            sb.Append("    type = \"feishu\"").Append(Environment.NewLine);
            sb.Append(Environment.NewLine);
            sb.Append("    [projects.platforms.options]").Append(Environment.NewLine);
            sb.Append("      app_id = ").Append(TomlString(config.Feishu.AppId)).Append(Environment.NewLine);
            sb.Append("      app_secret = ")
              .Append(redact ? "\"[REDACTED]\"" : TomlString(config.Feishu.AppSecret))
              .Append(Environment.NewLine);
            sb.Append("      allow_from = ").Append(TomlString(config.Feishu.AllowFrom)).Append(Environment.NewLine);

            // 非飞书平台原样保留:微信等平台是用户扫码绑定的资产,整块重写会把它抹掉。
            // 追加在飞书块之后,同属于该项目。缩进保持原样,块之间空一行。
            // 注意:脱敏输出绝不能包含这些块——微信平台的 options 里有 bearer token,
            // 属于凭据,不得回显到界面或日志。
            if (!redact && foreignPlatforms is { Count: > 0 })
            {
                foreach (string block in foreignPlatforms)
                {
                    sb.Append(Environment.NewLine);
                    sb.Append(block).Append(Environment.NewLine);
                }
            }
        }

        // 脱敏输出末尾追加一行注释,说明有多少个非飞书平台被保留但未回显。
        // 这样日志/界面能看出"有东西被藏起来了",又不泄露凭据内容。
        if (redact && foreignPlatforms is { Count: > 0 })
        {
            sb.Append(Environment.NewLine);
            sb.Append("# 另保留 ").Append(foreignPlatforms.Count)
              .Append(" 个非飞书平台(内容含凭据,不在此回显)").Append(Environment.NewLine);
        }

        return sb.ToString();
    }

    /// <summary>TOML 基础字符串转义(反斜杠/双引号/控制字符)。</summary>
    private static string TomlString(string value)
    {
        var sb = new StringBuilder("\"");
        foreach (char c in value)
        {
            switch (c)
            {
                case '\\':
                    sb.Append("\\\\");
                    break;
                case '"':
                    sb.Append("\\\"");
                    break;
                case '\n':
                    sb.Append("\\n");
                    break;
                case '\r':
                    sb.Append("\\r");
                    break;
                case '\t':
                    sb.Append("\\t");
                    break;
                default:
                    if (char.IsControl(c))
                    {
                        sb.Append("\\u").Append(((int)c).ToString("X4"));
                    }
                    else
                    {
                        sb.Append(c);
                    }

                    break;
            }
        }

        return sb.Append('"').ToString();
    }
}
